confluentinc/kafka-connect-storage-cloud

kafka-connect-s3/docs/configuration_options.rst, kafka-connect-s3/docs/s3_connector.rst
We should mention this parameter is per partition. @kkonstantine can you double check me? Should be quick.
=> flush.size doc fixes

kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkConnectorConfig.java, kafka-connect-s3/src/main/java/io/confluent/connect/s3/TopicPartitionWriter.java, kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/avro/AvroRecordWriterProvider.java, kafka-connect-s3/src/test/java/io/confluent/connect/s3/DataWriterAvroTest.java
Add support for Avro compression codec. This will enable Avro file compression with codecs provided by Avro library.
=> Enable compression of output Avro files 

kafka-connect-s3/docs/changelog.rst
=> 3.3.0-changelog

kafka-connect-s3/docs/s3_connector.rst
The HDFS connector has a section that outlines the details of the schema.compatibility setting. The S3 connector has a similar setting with the same behavior, so the S3 documentation should also have this same section.
=> CC-871 Added schema evolution section to S3 documentation (doc changes only)

kafka-connect-s3/docs/configuration_options.rst
* Bring configuration option up to date for 3.2.2.
=> CC-872: Update default part.size number in S3 docs and more.

README.md
Addresses https://github.com/confluentinc/kafka-connect-storage-cloud/issues/94
=> Add instructions about upstream builds

kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/avro/AvroRecordWriterProvider.java, kafka-connect-s3/src/test/java/io/confluent/connect/s3/DataWriterAvroTest.java, kafka-connect-s3/src/test/java/io/confluent/connect/s3/S3SinkTaskTest.java, kafka-connect-s3/src/test/java/io/confluent/connect/s3/format/avro/AvroUtils.java
* Follows from: https://github.com/confluentinc/kafka-connect-hdfs/issues/130
* Equivalent to: https://github.com/confluentinc/kafka-connect-hdfs/pull/176
=> HOTFIX: Handle primitive types in AvroFormat

kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkConnectorConfig.java, kafka-connect-s3/src/test/java/io/confluent/connect/s3/DataWriterAvroTest.java
Signed-off-by: Arjun Satish <arjun@confluent.io>
=> CC-1299: Refactor this code to use the AVRO_CODEC config key from storage-common

kafka-connect-s3/docs/s3_connector.rst
See related https://github.com/confluentinc/kafka-connect-hdfs/pull/300
=> Make confluent CLI command output shared

kafka-connect-s3/docs/s3_connector.rst
Related https://github.com/confluentinc/docs/pull/807
=> Fix for moved /includes content

kafka-connect-s3/docs/s3_connector.rst
This only changes the documentation.
=> CC-1791: Added compression options to raw value example

kafka-connect-s3/docs/s3_connector.rst
https://confluentinc.atlassian.net/browse/DOCS-802
https://confluentinc.atlassian.net/browse/DOCS-809
=> DOCS-802 - Fix Connect timestamp extractor property

kafka-connect-s3/src/main/java/io/confluent/connect/s3/TopicPartitionWriter.java, kafka-connect-s3/src/test/java/io/confluent/connect/s3/TopicPartitionWriterTest.java
This reverts commit 3bc8a482cdf2f8dc14af09526480180e736f129b.
Reverts adding append.late.data config to avoid inclusion in a release yet.
=> Revert "CC-2313 Handle late arriving records in storage cloud sink connectors (#187)"

kafka-connect-s3/src/main/java/io/confluent/connect/s3/storage/S3OutputStream.java
=> MINOR: New log for SSE

kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkConnectorConfig.java, kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/parquet/ParquetRecordWriterProvider.java, kafka-connect-s3/src/test/java/io/confluent/connect/s3/DataWriterParquetTest.java, kafka-connect-s3/src/test/java/io/confluent/connect/s3/S3SinkConnectorConfigTest.java
Use parquet.coded and enable compression for parquet format
=> CC-6565: Use parquet.codec and add compression options for Parquet format

kafka-connect-s3/src/main/java/io/confluent/connect/s3/TopicPartitionWriter.java
Previous log message would print the entire map instead of just the specific entry
The method is refactored to access every map entry once.
=> MINOR: Fix log message when tagging an S3 object

kafka-connect-s3/pom.xml, kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkConnector.java, kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkConnectorConfig.java, kafka-connect-s3/src/main/java/io/confluent/connect/s3/util/S3BucketCheck.java, kafka-connect-s3/src/test/java/io/confluent/connect/s3/S3SinkConnectorConfigTest.java, kafka-connect-s3/src/test/java/io/confluent/connect/s3/S3SinkConnectorTest.java
Addressing Jira issue CC-2539: Added a validator to check the format of S3 bucket name.
=> CC-2539: Added a validator to check the format of S3 bucket name

kafka-connect-s3/pom.xml
=> CC-9209: Fix the build

kafka-connect-s3/src/test/java/io/confluent/connect/s3/DataWriterAvroTest.java
=> MINOR: Remove unused prop from test (that is going away)

kafka-connect-s3/pom.xml
- Update docs URL path to exact path 
- Please let me know if I should target a different branch for this one and will do if needed.
- Update docs URL path to exact path
=> update pom.xml docs URL path

pom.xml
Use changes that remove avro-converter dependency in upstream repo https://github.com/confluentinc/kafka-connect-storage-common/pull/168 
Tracking in epic https://confluentinc.atlassian.net/secure/RapidBoard.jspa?rapidView=282&modal=detail&selectedIssue=CC-10193&assignee=5c58834895f91f3a042047b5
=> CC-12997: Update kafka-connect-storage-common to 10.0.2

Jenkinsfile, README.md, kafka-connect-s3/pom.xml, kafka-connect-s3/src/test/java/io/confluent/connect/s3/integration/README.md, kafka-connect-s3/src/test/java/io/confluent/connect/s3/integration/S3SinkConnectorIT.java
Reverts confluentinc/kafka-connect-storage-cloud#398
Will recommit to commit to 10.0.x
=> Revert "CCMSG-493: enable IT"

kafka-connect-s3/src/test/java/io/confluent/connect/s3/integration/README.md
=> MINOR: Revise readme for ITs

pom.xml
Parent has fixes that now need to be ported with an explicit bump
Bump the parent to the next patch release
=> CCMSG-1194: Upgrade parent and storage-common dependencies to 10.2.1

pom.xml
=> CCMSG-1259: Upgrade parent and storage-common dependencies to 10.2.2

Jenkinsfile
=> Disable concurrent builds 53x

Jenkinsfile
=> Disable concurrent builds 55x

kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkTask.java, kafka-connect-s3/src/test/java/io/confluent/connect/s3/integration/S3SinkConnectorIT.java
=> MINOR: Remove guava usage and superfluous template arguments.

CONTRIBUTING.md
=> MINOR: Contribution guidelines for developers

README.md
=> Update README.md to include link to contribution guidelines

kafka-connect-s3/src/main/java/io/confluent/connect/s3/util/S3ProxyConfig.java
=> Don't log full proxy config, don't log configuration @ info level

kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/avro/AvroRecordWriterProvider.java, kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/bytearray/ByteArrayRecordWriterProvider.java, kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/json/JsonRecordWriterProvider.java, kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/parquet/ParquetRecordWriterProvider.java, pom.xml
Parent brings in updates for jackson and protobuf-java cve's
Also causes tests to fail on missing junit-jupiter methods, as well as checkstyle errors. this pr addresses those as well.
=> CCMSG-1738: Upgrade parent pom for jackson and protobuf-java cve updates

pom.xml
=> CCMSG-1743 upgraded storage-common to resolve jackson-databind 2.13.2 CVE

kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/KeyValueHeaderRecordWriterProvider.java, kafka-connect-s3/src/test/java/io/confluent/connect/s3/TopicPartitionWriterTest.java
https://confluentinc.atlassian.net/browse/RCCA-6501
=> CCMSG-1772 | Remove the logging of sink record in case of data exception.

kafka-connect-s3/pom.xml, pom.xml
CVE fix for Guava dependency. Bump version to > v30
=> CCMSG-1688: CVE fix for Guava dependency

kafka-connect-s3/licenses.html, kafka-connect-s3/pom.xml, pom.xml
This is an autogenerated pull request by `pint` due to a merge conflict failure seen during [`pint merge`](http://go/pint-merge-service).
1. Resolve all conflicts (either via web editor or the command line)
2. Commit merge
3. Obtain approvals from reviewers
4. **(IMPORTANT)** After obtaining approvals, click the dropdown menu on the merge button and select **"Create a merge commit"** 
5. Click the "Merge pull request" button
6. Re-run [`pint merge`]( http://go/pint-merge-service)
NOTE: **"Create a merge commit"** option must be used to ensure all commits from the head branch is added to the base branch.
Please reach out to the Developer Productivity team on Slack at #devprod-eng or #devprod-oncall
=> Merge Conflict Resolution (from 5.5.x to 10.0.x)

pom.xml
Upgrade to new storage-common 11.0.11
=> Upgrade storage common to 11.0.11

kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkConnectorConfig.java, kafka-connect-s3/src/main/java/io/confluent/connect/s3/storage/ByteBuf.java, kafka-connect-s3/src/main/java/io/confluent/connect/s3/storage/ElasticByteBuffer.java, kafka-connect-s3/src/main/java/io/confluent/connect/s3/storage/S3OutputStream.java, kafka-connect-s3/src/main/java/io/confluent/connect/s3/storage/SimpleByteBuffer.java, kafka-connect-s3/src/test/java/io/confluent/connect/s3/storage/ElasticByteBufferTest.java
Same PR as in: https://github.com/confluentinc/kafka-connect-storage-cloud/pull/419
But rebase on master and do some updates.
- [* ] no
- [ *] Unit tests
=> Elastic byte buffer for S3OutputStream (base on master)

kafka-connect-s3/pom.xml, pom.xml
Branch cut - 10.1.x . Can't push directly to master, hence the branch cut changes to master weren't commited completely. 
Adding the version changes manually.
=> Update master to reflect new branch cut changes

kafka-connect-s3/pom.xml
This is to upgrade S3 sdk version
CP
=> Upgrade s3 sdk to 1.12.268

kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkConnectorValidator.java, kafka-connect-s3/src/test/java/io/confluent/connect/s3/S3SinkConnectorValidatorTest.java
https://confluentinc.atlassian.net/browse/CCMSG-2233
https://github.com/confluentinc/kafka-connect-storage-cloud/issues/545
Removed compression type validation for none compression type
```sh
➜  connect-aws-s3-sink git:(master) ✗ CONNECTOR_ZIP=/Users/ajain/projects/kafka-connect-storage-cloud/kafka-connect-s3/target/components/packages/confluentinc-kafka-connect-s3-10.0.11-SNAPSHOT.zip ./s3-sink.sh
15:46:42 ℹ️ 💫 Using default CP version 7.1.1
15:46:42 ℹ️ 🎓 set TAG environment variable to specify different version, see https://kafka-docker-playground.io/#/how-to-use?id=🎯-for-confluent-platform-cp
15:46:43 ℹ️ 👷🛠 Re-building Docker image vdesabou/kafka-docker-playground-connect:7.1.1 to include confluentinc/kafka-connect-s3:latest
[+] Building 17.9s (6/6) FINISHED …
```
=> CCMSG-2233: Fixed compression validation for custom format and compression type none

pom.xml
licenses.version is set to old value.
Updating licenses.version to 5.5.13
=> Update license version

pom.xml
https://confluentinc.atlassian.net/browse/CCMSG-2293
Bumping hadoop Version to 3.2.4
=> CCMSG-2293 : bumping hadoop version

pom.xml
parent version contais SNAPSHOt version
mapped to correct version.
=> Removing SNAPSHOT version 

pom.xml
while release, it is picking SNAPshot version.
Updating it with proper version
=> fixing release issue

pom.xml
IT testcases are failing in 5.5.x
included jetty modules
=> Fix Integration Test in 5.5.x

pom.xml
https://confluentinc.atlassian.net/browse/CC-18651
https://confluentinc.atlassian.net/browse/CC-18579
https://confluentinc.atlassian.net/browse/CC-18574
https://confluentinc.atlassian.net/browse/CC-18572
Update version to 1.5.2 from 5.5.x to master branches.
Ping merge after this PR merge
-  Tested via docker playground using S3 Sink connector.
=> Update version for org.codehaus.jettison_jettison to 1.5.2

pom.xml
=> CC-18651 | Bump jettison version to 1.5.2

pom.xml
=> MINOR: Fix jetty-util test dependency for integration test.

service.yml
Setting up semaphore for this repo
=> added service.yml for setting up semaphore pipeline

kafka-connect-s3/pom.xml, kafka-connect-s3/src/test/java/io/confluent/connect/s3/integration/BaseConnectorIT.java, kafka-connect-s3/src/test/java/io/confluent/connect/s3/integration/S3SinkConnectorIT.java, kafka-connect-s3/src/test/java/io/confluent/connect/s3/integration/S3SinkDataFormatIT.java, pom.xml
Add integration tests for all SR backed types.
=> CC-19528 | Add Integration tests for SR backed types.

kafka-connect-s3/pom.xml, kafka-connect-s3/src/test/java/io/confluent/connect/s3/integration/BaseConnectorIT.java, kafka-connect-s3/src/test/java/io/confluent/connect/s3/integration/S3SinkConnectorIT.java, kafka-connect-s3/src/test/java/io/confluent/connect/s3/integration/S3SinkDataFormatIT.java, pom.xml
=> Merge conflict 10.3.x

kafka-connect-s3/pom.xml, pom.xml
Update json-smart and jettison to address CVEs: CVE-2023-1370  CVE-2023-1436
=> CCMSG-2416 CCMSG-2417 update json-smart and jettison

kafka-connect-s3/pom.xml, pom.xml
Following up on https://confluentinc.atlassian.net/browse/ESC-581
this is plugging all the currently known CVEs for Citi connector ingestion.
=> ESC-581: pin dependencies to resolve CVEs for Citi escalation

kafka-connect-s3/pom.xml, pom.xml
This is an autogenerated pull request by `pint` due to a merge conflict failure seen during [`pint merge`](http://go/pint-merge-service).
1. Resolve all conflicts (either via web editor or the command line)
2. Commit merge
3. Obtain approvals from reviewers
4. **(IMPORTANT)** After obtaining approvals, click the dropdown menu on the merge button and select **"Create a merge commit"** 
5. Click the "Merge pull request" button
6. Re-run [`pint merge`]( http://go/pint-merge-service)
NOTE: **"Create a merge commit"** option must be used to ensure all commits from the head branch is added to the base branch.
Please reach out to the Developer Productivity team on Slack at #devprod-eng or #devprod-oncall
=> Merge Conflict Resolution (from 10.3.x to 10.4.x)

kafka-connect-s3/pom.xml, kafka-connect-s3/src/test/java/io/confluent/connect/s3/integration/BaseConnectorIT.java, pom.xml
https://confluentinc.atlassian.net/browse/CC-21863
https://confluentinc.atlassian.net/browse/CC-22382
Latest scan: https://twistlock.tools.confluent-internal.io/#!/monitor/vulnerabilities/images/ci?search=Confluent%20Public%20Repo%20PR%20builder%2Fkafka-connect-storage-cloud%2FPR-692
Ignore the snappy alert as per this: https://confluent.slack.com/archives/C018M1KK0Q2/p1697819611568809?thread_ts=1694757279.047599&cid=C018M1KK0Q2
Zookeeper vulnerability - I tried resolving it but we are running into some weird issues due to it in the test framework.
=> [CC-21863] CVE fixes

kafka-connect-s3/src/test/java/io/confluent/connect/s3/S3SinkConnectorFaultyS3Test.java
=> [CC-21863] Resolve plugin.discovery error

kafka-connect-s3/src/main/java/io/confluent/connect/s3/TopicPartitionWriter.java
=> MINOR: Fix checkstyle error.

kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkTask.java
=> MINOR: Add diagnostic info for topic partition assignments

kafka-connect-s3/pom.xml, pom.xml
Revert commits as release failed in last release.
=> Revert commits

kafka-connect-s3/src/test/java/io/confluent/connect/s3/S3SinkConnectorConfigTest.java, kafka-connect-s3/src/test/java/io/confluent/connect/s3/storage/S3StorageTest.java
=> Fix S3SinkConnectorConfigTest and S3StorageTest

pom.xml
=> CC-25322 Bump kafka-connect-storage-common-parent

.github/CODEOWNERS
Remove team1 and have connect-cloud as code owners
=> Update CODEOWNERS to connect-cloud

kafka-connect-s3/pom.xml, pom.xml
This is an autogenerated pull request by `pint` due to a merge conflict failure seen during [`pint merge`](http://go/pint-merge-service).
1. Resolve all conflicts (either via web editor or the command line)
2. Commit merge
3. Obtain approvals from reviewers
4. **(IMPORTANT)** After obtaining approvals, click the dropdown menu on the merge button and select **"Create a merge commit"** 
5. Click the "Merge pull request" button
6. Re-run [`pint merge`]( http://go/pint-merge-service)
NOTE: **"Create a merge commit"** option must be used to ensure all commits from the head branch is added to the base branch.
Please reach out to the Developer Productivity team on Slack at #devprod-eng or #devprod-oncall
=> Merge Conflict Resolution (from 10.0.x to 10.1.x)

pom.xml
=> CC-26361 Bump commons-configuration2

kafka-connect-s3/pom.xml, pom.xml
Fixes https://confluentinc.atlassian.net/browse/CC-26516
https://confluentinc.atlassian.net/browse/CC-26360
=> CC-26516 Bump aws version

kafka-connect-s3/pom.xml, pom.xml
Revert due to an issue in publishing of artifact
=> Revert 10.5.13 release

kafka-connect-s3/pom.xml, pom.xml
Revert partially released version
=> Revert release 10.5.13

pom.xml
Refer to this comment: https://confluentinc.atlassian.net/browse/CC-28258?focusedCommentId=2997339
=> Update dnsjava version

kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkConnectorConfig.java, kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkTask.java
=> Pint Merge: Conflict resolution 10.1.x to 10.2.x

kafka-connect-s3/src/main/java/io/confluent/connect/s3/storage/S3OutputStream.java
=> Fix checkstyle

kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkConnectorConfig.java
=> Fix checkstyle due to NCSS

.semaphore/semaphore.yml, pom.xml
PR: https://github.com/confluentinc/airlock-kafka-connect-storage-cloud/pull/9
=> [CC-29196] Bump Protobuf java version (#9)

kafka-connect-s3/pom.xml, pom.xml
https://github.com/confluentinc/airlock-kafka-connect-storage-cloud/pull/17
=> Fix protobuf-java and common-io version (#17)

kafka-connect-s3/pom.xml, kafka-connect-s3/src/main/java/io/confluent/connect/s3/TopicPartitionWriter.java, kafka-connect-s3/src/test/java/io/confluent/connect/s3/TopicPartitionWriterTest.java, pom.xml
=> Pint merge 10.1.x

kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkTask.java
=> CC-28527 Close only the revoked topic partitions on close

kafka-connect-s3/pom.xml, kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkTask.java, pom.xml
This is an autogenerated pull request by `pint` due to a merge conflict failure seen during [`pint merge`](http://go/pint-merge-service).
1. Resolve all conflicts (either via web editor or the command line)
2. Commit merge
3. Obtain approvals from reviewers
4. **(IMPORTANT)** After obtaining approvals, click the dropdown menu on the merge button and select **"Create a merge commit"** 
5. Click the "Merge pull request" button
6. Re-run [`pint merge`]( http://go/pint-merge-service)
NOTE: **"Create a merge commit"** option must be used to ensure all commits from the head branch is added to the base branch.
Please reach out to the Developer Productivity team on Slack at #devprod-eng or #devprod-oncall
=> Merge Conflict Resolution (from 10.1.x to 10.2.x)

kafka-connect-s3/src/main/java/io/confluent/connect/s3/TopicPartitionWriter.java
=> CC-29287: Write actual record in DLQ instead of projected record

pom.xml
https://confluentinc.atlassian.net/browse/CVE-4398
Update hadoop version to 3.4.0
=> Update hadoop-common: 3.4.0

pom.xml
Upgrade kafka-connect-storage-common-parent to the current latest version- 11.2.20, to resolve CVEs
=> CC-31173: Upgrade kafka-connect-storage-common-parent

pom.xml
https://confluentinc.atlassian.net/browse/CC-34183
Updated the common-beanutils dependency to 1.11.0
=> CVE fix - Update common-beanutils version to 1.11.0
