confluentinc/kafka-connect-storage-cloud

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/json/JsonRecordWriterProvider.java
Jackson as default root value separate a single white space.
Changing it to the line separator used by the system running the connector. (`"\n"` for Unix systems, `"\r\n"` for Windows systems).
> CC-513: Newline is not appended between records when using JsonFormat

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkConnector.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/S3SinkConnectorTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/S3SinkTaskTest.java
* Needed by the framework for better management of the connector.
* Fixes CC-537: S3SinkConnector needs to extend SinkConnector for runtime class resolution
> HOTFIX: S3SinkConnector should extend SinkConnector

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkConnectorConfig.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/storage/S3OutputStream.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/S3SinkTaskTest.java
This option is helpful for writing cross account.
In our use case, our Kafka Connect instance runs in a separate account from where our destination S3 buckets live. We want to be able to specify `BucketOwnerFullControl` so that the destination account has read and write access to the objects Kafka Connect is writing. The default `Private` acl allows access only from the account that originally wrote the data.
> Add s3.canned.acl config

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkConnectorConfig.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/bytearray/ByteArrayFormat.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/bytearray/ByteArrayRecordWriterProvider.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/DataWriterByteArrayTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/TestWithMockedS3.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/format/bytearray/ByteArrayUtils.java
- pom.xml
As @kkonstantine suggested in https://github.com/confluentinc/kafka-connect-storage-cloud/issues/22#issuecomment-287885581, availability of `ByteArrayConverter` since 0.11.0.0 allows us to skip parsing of message values completely and write them as is.
This PR adds a `ByteArrayFormat` and `ByteArrayRecordWriterProvider` to wrap the new converter.
I've marked this WIP as I'd like to gather some feedback about whether there are other potential approaches and whether there are additional options we'd need to see for this to be mergeable.
> Add ByteArrayFormat

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/storage/S3Storage.java
To connect to an S3 compatible service, connector should be able to accept both URL and region together.
Refer https://github.com/minio/minio/issues/3978 for example
> Fix new client creation to cater for URLs and region together

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/TopicPartitionWriter.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/TopicPartitionWriterTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/util/FileUtils.java
Hi,
It would be useful to allow the s3 connector to write at the root of the bucket. It's fairly straightforward to implement this with the existing configs.
If topic.dir is either set with a blank value or a slash the connector should write at the root of the bucket
> Allow to write records at the root of the bucket

- pom.xml
This fixes the build and allows the tests
to run with Java 9.
> Update to PowerMock 2.0.x and Mockito 2

- kafka-connect-s3/src/test/java/io/confluent/connect/s3/TopicPartitionWriterTest.java
Test for https://github.com/confluentinc/kafka-connect-storage-common/pull/55
> MINOR: Test case for CC-1489: NPE on records with null timestamp

- kafka-connect-s3/src/test/java/io/confluent/connect/s3/TopicPartitionWriterTest.java
Related to confluentinc/kafka-connect-storage-common#53.
> Support for multiple fields in field partitioner

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkConnectorConfig.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/bytearray/ByteArrayRecordWriterProvider.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/json/JsonRecordWriterProvider.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/storage/CompressionType.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/storage/S3OutputStream.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/DataWriterByteArrayTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/DataWriterJsonTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/TestWithMockedS3.java
Addresses the final piece of https://github.com/confluentinc/kafka-connect-storage-cloud/issues/22
> Add gzip compression support for json and byte array formats

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/storage/S3OutputStream.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/DataWriterByteArrayTest.java
There is two overloaded versions of `write` method on S3OutputStream. In situation when stream `buffer` becomes full by calling `public void write(byte[] b, int off, int len)`, and then `public void write(int b)` called for some reason, we'll get BufferOverflowException. To avoid it, we do check `!buffer.hasRemaining()` in both methods before returning and flush buffer if it's full.
Just to provide more context, I got this exception when extending `kafka-connect-s3` with custom format that uses LZOP compression before sending data to S3. In this case LZOP API finalizes compression of the chunk of data by writing a byte at the end of the S3 stream. If buffer of the stream is full by that time, I get BufferOverflowException. To be consistent, both methods now check if buffer is full before …
> Fix for BufferOverflowException in S3OutputStream

- kafka-connect-s3/docs/README.md
- kafka-connect-s3/docs/configuration_options.rst
- kafka-connect-s3/docs/s3_connector.rst
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkConnectorConfig.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/DummyAssertiveCredentialsProvider.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/S3SinkConnectorConfigTest.java
Changes in this PR:
* Logic which checks whether class specified in `s3.credentials.provider.class` implements `Configurable` and passes all properties prefixed by `s3.credentials.provider.configs.` to that class if it does;
* Unit test to exercise positive scenario of a configurable credential provider;
* Doc changes.
> CC-1497. Added logic for passing a subset of configs down to configurable credentials provider

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkConnectorConfig.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/storage/S3OutputStream.java
This resolves issue #79 (Support AWS KMS and SSE-C). Example usage:
```
s3.ssea.name=AES256
s3.sse.customer.key=MzJfYnl0ZV9zdHJpbmdfbmVlZGVkX2Zvcl9BRVMyNTY=
```
> Extend the existing SSE support to enable Customer (provided) Keys SSE-C

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/TopicPartitionWriter.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/TopicPartitionWriterTest.java
We had issues where late-arriving records would cause rollups of s3 files when they were part of the previous partition. 
For example, consider an s3-sink configured for hourly rollups. Now, if we receive records from a previous partition ("late-arriving") then a separate rollup is triggered, so that the record does not appear in the wrong partition. Strictly speaking, this is expected behavior. However, there is demand to have an option to avoid these extra rollups in the event of a system with freqent late-arriving records causing pileup of numerous small files.
The proposed strategy is to add a new "strict" config option that lets users choose to put records from a previous partition in the current partition if it arrives late. By default, we will be in "strict" mode, preserving our …
> CC-2313 Handle late arriving records in storage cloud sink connectors

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/TopicPartitionWriter.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/TopicPartitionWriterTest.java
Prior to this fix, current partition was not reset after a commit.
This caused records intended for later partitions to be placed in
currently open partition
Fix includes new tests where files from earlier and later partitions
are added and flushed and asserted against
> CC-2619 Bugfix for append.late.data configuration rotating partitions

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/TopicPartitionWriter.java
This is how the log message will look like now: 
```
[2018-04-23 10:57:41,935] TRACE Should apply periodic time-based rotation (rotateIntervalMs: '60000', baseRecordTimestamp: 'null', timestamp: 'null', encodedPartition: 'partition=12', currentEncodedPartition: 'partition=12')? false (io.confluent.connect.s3.TopicPartitionWriter:310)
```
Signed-off-by: Arjun Satish <arjun@confluent.io>
> MINOR: Add all parameters which decide the value of periodicRotation

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/TopicPartitionWriter.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/TopicPartitionWriterTest.java
Extending Partitioner and Extractor to accept a timestamp gives flexibility
for the calling function to inject desired behavior in some cases.
This has been particularly useful in getting consistent timestamps
in a wallclock based partitioners to return the same encodedPartition
for the same batch of records, preventing small files being created
across partition boundaries
Depends on https://github.com/confluentinc/kafka-connect-storage-common/pull/88
> CC-2617: Accept timestamp for wallclock instances to assure consistency

- kafka-connect-s3/pom.xml
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/DataWriterAvroTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/TestWithMockedS3.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/TopicPartitionWriterTest.java
- kafka-connect-s3/src/test/resources/log4j.properties
Also upgrade the S3Mock library from 0.1.5 (on Scala 2.11) to 0.2.5 (on Scala 2.12), which incorporates a number of bug fixes. This is to take advantage of a new `S3Mock.shutdown()` method that properly closes the Akka framework and HTTP listener created in the S3Mock object. For some reason, these still-bound HTTP listeners are not a problem on Java 8, but with Java 11 they prevent the next test from binding to the address and cause the test to fail.
With these changes, the build passes on both Java 8 and Java 11.
> CC-3035: Upgrade the S3Mock library so the module builds on Java 8 and Java 11

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/TopicPartitionWriter.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/TopicPartitionWriterTest.java
This seems to be cruft left over from an earlier refactor that was only used in the unit tests.
> CC-4969 MINOR: Remove Unused S3Storage object from TopicPartitionWriter

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkTask.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/TopicPartitionWriter.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/DataWriterAvroTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/TestWithMockedS3.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/TopicPartitionWriterTest.java
The connector so far has treated failures that occur when the output stream is closed as retriable only when `rotate.schedule.interval.ms` is set and it needs to flush outstanding records due to inactivity. 
However, offsets are not reset correctly, and retrying after the timeout expires might result in records being skipped as described in https://github.com/confluentinc/kafka-connect-storage-cloud/issues/269
This fix applies proper reset to the start offset that allows the consumer of a task to rewind correctly and considers any failure during file-commits (finalization of uploads) as a retriable exception.
> CC-6801: Retry effectively on retriable failures while closing files

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkTask.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/TopicPartitionWriter.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/DataWriterAvroTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/TestWithMockedS3.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/TopicPartitionWriterTest.java
The connector so far has treated failures that occur when the output stream is closed as retriable only when rotate.schedule.interval.ms is set and it needs to flush outstanding records due to inactivity.
However, offsets are not reset correctly, and retrying after the timeout expires might result in records being skipped as described in #269
This fix applies proper reset to the start offset that allows the consumer of a task to rewind correctly and considers any failure during file-commits (finalization of uploads) as a retriable exception.
> CC-6801: Retry effectively on retriable failures (backport to java 7 branches)

- pom.xml
* Upgrade commons-beanutils to 1.9.4
* Exclude commons-beanutils-core
* Exclude jetty-util
> MINOR: Upgrade bugfix versions of dependencies to avoid CVEs

- kafka-connect-s3/pom.xml
Simple upgrade of the AWS SDK to the next bugfix version. 
Upgrade will also resolve https://github.com/confluentinc/kafka-connect-storage-cloud/issues/288 and will add support for the AWS_ROLE_ARN and AWS_WEB_IDENTITY_TOKEN_FILE environment variables.
> MINOR: Upgrade AWS SDK to 1.11.725

- checkstyle/suppressions.xml
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkConnectorConfig.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkTask.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/TopicPartitionWriter.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/storage/S3Storage.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/S3SinkConnectorConfigTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/TestWithMockedS3.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/TopicPartitionWriterTest.java
PR for https://github.com/confluentinc/kafka-connect-storage-cloud/issues/201
This PR gives the S3 Connector Plugin the option to add s3 object level tags for starting offset, ending offset, and total record count of a given file. This should provide users a greater ability to track and monitor records written to s3.
> S3 Object Level Tagging for Offsets & Record Counts

- kafka-connect-s3/pom.xml
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkConnectorConfig.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/storage/CompressionType.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/storage/S3OutputStream.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/DataWriterByteArrayTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/DataWriterJsonTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/S3SinkConnectorConfigTest.java
This change will allow users to specify a specific level of compression when using the gzip compression type with Json or ByteArray formats.
> CC-8085: Allow setting compression level for gzip in Json and ByteArray formats

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkConnectorConfig.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/storage/S3Storage.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/DummyAssertiveCredentialsProvider.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/storage/S3StorageTest.java
Hello there, here is a functionality add that allows for secret/access key pairs to be defined for each connector instance in a connect cluster.  There are two new connector config settings and if they are not null the _AWSStaticCredentialsProvider_ is used and the credentials passed instead of using the provider chain that uses the environment variables or system properties that can't be set per connector.  Features like AssumeRole are the best practice in AWS itself but for devices that emulate the S3 API these kind of credential options are important.  Also, notice that this feature exposes this issue (https://github.com/aws/aws-sdk-java/issues/1256) but can be easily fixed when the AWS SDK version is increased.
> CC-7892: Introduce configuration properties for key and secret to easily define credentials per connector instance

- kafka-connect-s3/pom.xml
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/auth/AwsAssumeRoleCredentialsProvider.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/S3SinkConnectorConfigTest.java
Add an AWSCredentialsProvider that uses STSAssumeRoleSessionCredentialsProvider to assume an IAM Role. This allows the worker to write S3 objects that are owned by the bucket owner and not the Kafka Connect worker AWS Account.
> Add AWS IAM Assume Role credentials provider

- kafka-connect-s3/pom.xml
Adapting temporarily to https://github.com/aws/aws-sdk-java/issues/1919 until a newer version of httpclient is inherited by the imported hadoop or kafka-connect-storage-common dependencies. 
Without this PR a warning is issued every time `S3Storage` instantiates a new AWS S3 client
``WARN NoSuchMethodException was thrown when disabling normalizeUri. This indicates you are using an old version (< 4.5.8) of Apache http client. It is recommended to use http client version >= 4.5.9 to avoid the breaking change introduced in apache client 4.5.7 and the latency in exception handling. See https://github.com/aws/aws-sdk-java/issues/1919 for more information (com.amazonaws.http.apache.utils.ApacheUtils:246)``
> MINOR: Pin httpclient dependency to 4.5.9 to silence warning by the AWS SDK

- pom.xml
This PR explicitly excludes `jackson-mapper-asl` from being pulled in with `hadoop-common`. Code inspection indicates that the jar is not being used and can be removed. Passing muckrake system tests - https://jenkins.confluent.io/job/system-test-confluent-platform-branch-builder/3626/
> CC-8170: Exclude jackson-mapper-asl and commons-beanutils from hadoop-common import

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkTask.java
These two variables may become out-of-sync if instantiating a
TopicPartitionWriter throws an exception. This causes a NullPointerException
in preCommit and close when the assignment includes a topic partition without
a writer. Instead, the topicPartitionWriters map should be the source of truth
for the connector's cleanup and offset commit functionality.
Signed-off-by: Greg Harris <gregh@confluent.io>
> CC-8809: Replace assignments variable with topicPartitionWriters.keySet

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkTask.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/avro/AvroRecordWriterProvider.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/bytearray/ByteArrayRecordWriterProvider.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/json/JsonRecordWriterProvider.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/DataWriterAvroTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/DataWriterByteArrayTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/DataWriterJsonTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/S3SinkTaskTest.java
Why
-----
TopicPartitionWriter threw "SchemaProjectorException( "Switch between schema-based and schema-less data is not supported");" from storage common, despite having an AvroConverter, which we would expect to require every record to have a schema. The exceptional case, it turns out, is a null-valued schema which can have no schema. This alerted us that our original implementation of null-value-behavior in the writerprovider was carrying an assumption that the null-valued record would be well-handled by the topicpartitionwriter, which in this case, is not.
How
------
Moved the `nullValueBehavior` logic from the WriterProvider to be much earlier in Task.put, so we can continue to the next record before it can throw escalations or waste resources.
Testing
-----
Unit test included for …
> Move null value handling earlier in SinkTask put

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkConnectorConfig.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/S3SinkConnectorConfigTest.java
The `timezone` configuration is not being validated when the `TimeBasedPartitioner` is not set. This results in a runtime error when the `rotate.schedule.interval.ms` is used and an invalid or no `timezone` value is set. 
Validate the `timezone` configuration whenever set, and expect the `timezone` configuration to be set when `rotate.schedule.interval.ms` is used. 
All storage sink connectors that use the timezone configuration.
Backporting to TBD.
> CC-9753: Validate timezone configuration with rotate.schedule.interval.ms

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkConnectorConfig.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/storage/S3Storage.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/S3SinkConnectorTestBase.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/TestWithMockedS3.java
The connector since the beginning has been explicitly choosing to use path style access for S3 buckets in its requests. This access type is being deprecated and removed in Sept 30, 2020 for _new_ buckets on S3 that are created after that date. 
Addresses issue: https://github.com/confluentinc/kafka-connect-storage-cloud/issues/337
A configuration property `s3.path.style.access.enabled` is introduced to control the behavior. The behavior is matching the current existing behavior and will be backported to previous connector versions. A new connector version will be generated in a follow up that will have virtual hosted access as the default. 
S3 source connector
End to end tests with buckets in several regions and testing with and without setting `store.url`. 
See above
> CC-11480: Add configuration property to choose between path style and virtual hosted bucket access to S3

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkConnectorConfig.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/storage/S3Storage.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/S3SinkConnectorTestBase.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/TestWithMockedS3.java
Back port of https://github.com/confluentinc/kafka-connect-storage-cloud/pull/356
> CC-11480: Add configuration property to choose between path style and virtual hosted bucket access to S3 (back port to 5.0.x)

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/storage/S3OutputStream.java
`e.getCause` returns the cause of `e` (or null), so we will lose `e` from the stack trace.
Here is a real example, we can't even know what `e` actually is:
```
Caused by: java.io.IOException: Part upload failed:
at io.confluent.connect.s3.storage.S3OutputStream.uploadPart(S3OutputStream.java:135)
at io.confluent.connect.s3.storage.S3OutputStream.uploadPart(S3OutputStream.java:119)
at io.confluent.connect.s3.storage.S3OutputStream.write(S3OutputStream.java:107)
at java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:253)
at java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:211)
at java.util.zip.GZIPOutputStream.write(GZIPOutputStream.java:145)
at java.io.FilterOutputStream.write(FilterOutputStream.java:97)
at …
```
> MINOR: Restore the complete hierarchy of exceptions during failures in part upload

- checkstyle/suppressions.xml
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkConnectorConfig.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkTask.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/KeyValueHeaderRecordWriterProvider.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/RecordView.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/RecordViewSetter.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/RecordViews.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/avro/AvroRecordWriterProvider.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/bytearray/ByteArrayRecordWriterProvider.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/json/JsonRecordWriterProvider.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/parquet/ParquetRecordWriterProvider.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/storage/S3Storage.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/util/Utils.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/DataWriterAvroTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/S3SinkConnectorConfigTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/TopicPartitionWriterTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/format/RecordViewSetterTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/format/RecordViewsTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/util/UtilsTest.java
This PR adds the ability for the connector to write record keys and headers to separate key and header files if desired. 
The updated code exposes new connector configurations that allow the user to specify if they want to write the contents from the Kafka record key and header to files at the destination in addition to the original value file. 
The connector achieves this by introducing new configs along with a `RecordView` interface and `KeyValueRecordProvider` class.  We introduce our own `RecordWriterProvider` that provides an abstraction so that the `TopicPartitionWriter`  class can write  these new files without any code changes.
**KeyValueHeaderRecordWriterProvider**
This class provides an abstraction for writing, committing and closing all three header, key and value files. …
> CC-7933: Support writing key and headers to S3 in S3 sink connector

- Jenkinsfile
- kafka-connect-s3/pom.xml
- pom.xml
We need the release maven plugin for independent releases. Also, some adjustment in version variables
Add the plugin and apply fixes
In all community available connectors formerly shipping with CP
master only. 10.0.x will be created after this commit.
> CC-11859: Add release maven plugin and prepare 10.0 release

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/KeyValueHeaderRecordWriterProvider.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/TopicPartitionWriterTest.java
Writing empty headers should also throw an exception when `store.kafka.headers` is on. 
Add empty check along existing null check.
> CC-11945: Fix empty header check for storing headers

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/TopicPartitionWriter.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/avro/AvroRecordWriterProvider.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/bytearray/ByteArrayRecordWriterProvider.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/json/JsonRecordWriterProvider.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/storage/S3OutputStream.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/DataWriterAvroTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/DataWriterByteArrayTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/DataWriterJsonTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/S3SinkConnectorConfigTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/TestWithMockedS3.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/TopicPartitionWriterTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/storage/S3OutputStreamTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/storage/S3ProxyTest.java
Signed-off-by: Lev Zemlyanov <lev@confluent.io>
the connector will retry non-retriable S3 exceptions i.e `InvalidAccessKey`
if [initiating an upload](https://github.com/confluentinc/kafka-connect-storage-cloud/blob/5.0.x/kafka-connect-s3/src/main/java/io/confluent/connect/s3/storage/S3OutputStream.java#L206-L210) throws an exception, it is wrapped in an `IOException`, which follows from [here](https://github.com/confluentinc/kafka-connect-storage-cloud/blob/5.0.x/kafka-connect-s3/src/main/java/io/confluent/connect/s3/storage/S3OutputStream.java#L130) to [here](https://github.com/confluentinc/kafka-connect-storage-cloud/blob/5.0.x/kafka-connect-s3/src/main/java/io/confluent/connect/s3/storage/S3OutputStream.java#L156)
where it is [swallowed and …
> CC-12695: stop throwing retriable exceptions on non-retriable S3 errors

- kafka-connect-s3/pom.xml
Signed-off-by: Lev Zemlyanov <lev@confluent.io>
test containers brings in `commons-compress:1.18` which has a CVE
bump to `1.15.0` which uses `1.20` and set it to `test` scope because its a test dependency
twistlock is clean
backport to `5.5.x` where this CVE was introduced
> CC-12772: bump test containers version to addres commons-compress CVE

- pom.xml
Build issue
```
01:01:13  [ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare (default-cli) on project kafka-connect-storage-cloud: 
Can't release project due to non released dependencies :
01:01:13  [ERROR]     io.confluent:kafka-connect-storage-common:jar:10.0.0-SNAPSHOT:compile
01:01:13  [ERROR]     io.confluent:kafka-connect-storage-core:jar:10.0.0-SNAPSHOT:compile
01:01:13  [ERROR]     io.confluent:kafka-connect-storage-format:jar:10.0.0-SNAPSHOT:compile
01:01:13  [ERROR]     io.confluent:kafka-connect-storage-partitioner:jar:10.0.0-SNAPSHOT:compile
01:01:13  [ERROR] in project 'kafka-connect-storage-cloud' (io.confluent:kafka-connect-storage-cloud:pom:10.0.0-SNAPSHOT)
```
Bump parent to version that includes fix …
> MINOR: bump storage common parent

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkTask.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/TopicPartitionWriter.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/KeyValueHeaderRecordWriterProvider.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/bytearray/ByteArrayRecordWriterProvider.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/storage/S3OutputStream.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/S3SinkTaskTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/TopicPartitionWriterTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/integration/BaseConnectorIT.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/integration/S3SinkConnectorIT.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/storage/S3OutputStreamTest.java
The S3 Sink connector currently does not report faulty records to the DLQ. Having this functionality provides more information on failed records and is useful for debugging and monitoring purposes.
Add the `ErrantRecordReporter` introduced by [KIP-610](https://cwiki.apache.org/confluence/display/KAFKA/KIP-610%3A+Error+Reporting+in+Sink+Connectors) that writes failed records and their errors to the specified DLQ topic. The topic name can be specified by `errors.deadletterqueue.topic.name`.
1. Record value is `null` and `behavior.on.null.values` is `IGNORE`. (S3SinkTask)
2. The record was determined to be malformed on attempting write. (TopicPartitionWriter)
3. The record key is `null` but `write.record.keys` is turned on.
4. The record headers are `null` but `write.record.headers` is …
> CC-9723: DLQ support in S3 sink

- kafka-connect-s3/pom.xml
- pom.xml
Sync version of org.apache.httpcomponents:httpclient version and fix CVE
Use the one defined in kafka-connect-storage-common
Merge to master
> CC-13830: Upgrade S3 connector to use HttpClient defined in kafka-connect-storage-common

- checkstyle/suppressions.xml
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/TopicPartitionWriter.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/TopicPartitionWriterTest.java
There is an additional opportunity to catch and report an exception to the DLQ. 
Catch exception on `encodePartition` and report it to the DLQ using the reporter if available. 
`10.0.x` the earliest DLQ branch.
> CCMSG-861: Catch additional exception to report in DLQ

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/TopicPartitionWriter.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/TopicPartitionWriterTest.java
- pom.xml
Currently `ConnectException` is caught in the `TPW` when encoding a partition. 
Revise to a more appropriate `PartitionException` for the DLQ. 
Targeting to `10.0.x`
> MINOR: Upgrade storage common to 10.0.5 and catch PartitionException in TopicPartitionWriter's error handling

- pom.xml
commons-httpclient is brought in by transitive depency and is pretty old, their last update is 2007 and they are deprecated.
They contain a CVE https://confluentinc.atlassian.net/browse/SEC-1996
Switch to the new package https://mvnrepository.com/artifact/org.apache.httpcomponents/httpclient
All usages of commons-httpclient
Rely on existing tests.
> SEC-1996: Replace commons-httpclient with apache httpclient

- Jenkinsfile
- kafka-connect-s3/pom.xml
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/integration/S3SinkConnectorIT.java
- pom.xml
Enable IT for S3Sink
- [x ] no
- [*] Unit tests
- [*] Integration tests
```
mvn test
[INFO] Results:
[INFO] 
[INFO] Tests run: 152, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for kafka-connect-storage-cloud 5.5.4-SNAPSHOT:
[INFO] 
[INFO] kafka-connect-storage-cloud ........................ SUCCESS [  3.127 s]
[INFO] kafka-connect-s3 ................................... SUCCESS [01:24 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:28 min
[INFO] Finished at: 2021-04-05T14:35:50-04:00
[INFO] …
```
> ccmsg-494: enable IT for S3Sink

- kafka-connect-s3/pom.xml
Upgrade to the latest AWS SDK version
Fix CVE in jackson-dataformat-cbor
Currently jackson is pinned to version 2.10.5 from https://github.com/confluentinc/common
Because of this selection the transitive dependency `jackson-dataformat-cbor` imported from the AWS SDK is also being included in version 2.10.5. Instead of upgrading jackson for this connector only and on a patch release, it's preferred to exclude `jackson-dataformat-cbor` because it's unused by the connector and the way it uses AWS SDK for S3.
> CCMSG-1021: Upgrade AWS SDK to 1.11.1015 and exclude jackson-dataformat-cbor

- pom.xml
Signed-off-by: Lev Zemlyanov <lev@confluent.io>
build is broken due to missing jackson dependency 
add jackson dependency
backport to `5.2.x` where build is broken
> MINOR: fix build

- kafka-connect-s3/pom.xml
com.fasterxml.jackson.dataformat_jackson-dataformat-cbor 2.9.10 has a CVE:
[cvss:7.50] CVE-2020-28491 ['fixed in 2.11.4,  2.12.1']
Upgrade to 2.11.4 which has a fix
The version comes through dependency management from https://github.com/confluentinc/common/blob/5.2.x/pom.xml#L59
> Pin version of jackson-dataformat-cbor to 2.11.4

- pom.xml
This package is not used but bring in several transitive deps
We should remove and align with more recent branches. 
Applies only to 5.2.x
> MINOR: Remove unused dependency on kafka-connect-storage-hive in the 5.2.x release branch

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/json/JsonRecordWriterProvider.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/TopicPartitionWriterTest.java
Using the configs below results in a serialization exception. 
```
"store.kafka.headers": "true",
"headers.format.class": "io.confluent.connect.s3.format.json.JsonFormat"
```
Error
```
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.apache.kafka.connect.data.Struct and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: java.util.ArrayList[0])
at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1191)
```
Reported in https://github.com/confluentinc/kafka-connect-storage-cloud/issues/413. …
> CC-14987: Fix serialization when headers.format.class is json

- pom.xml
Fixes https://github.com/confluentinc/kafka-connect-storage-cloud/issues/316
Upgrade to hadoop 2.10.1 coming from storage-common
> Upgrade to hadoop common 2.10.1 for parquet support

- pom.xml
json-smart dependency 2.3 has a CVE.
Upgrade to CVE free version through parent.
> CCMSG-1146: Upgrade json-smart to 2.4.7 through parent

- kafka-connect-s3/pom.xml
Guava dependency not included in connector. For functioning environments it's being picked up from the Confluent Platform packages.
https://github.com/confluentinc/kafka-connect-storage-cloud/issues/444
Include dependency in connector package.
> CC-15510: Add guava dependency

- pom.xml
netty-codec 4.1.63 is vulnerable
Exclude this unused dependency
> CCMSG-1420 Exclude unused netty-codec dependency

- kafka-connect-s3/pom.xml
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkTask.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/KeyValueHeaderRecordWriterProvider.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/DataWriterAvroTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/DataWriterByteArrayTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/DataWriterJsonTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/DataWriterParquetTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/DataWriterTestBase.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/S3SinkTaskTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/integration/BaseConnectorIT.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/integration/S3SinkConnectorIT.java
Moving from this PR in forked repo:  https://github.com/confluentinc/kafka-connect-storage-cloud/pull/464
Generalize the DataWriterXXXTest unit test classes, moving much of the common code into a base class DataWriterTestBase in order to reduce redundancy as well as simplify doing unit tests of the issue being fixed in this PR.
No significant logic changes for the movement to base class, largely just cut+paste.
> Allow string match of formatting file extension to exist in the topic name (or elsewhere in the file besides the end)

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/parquet/ParquetRecordWriterProvider.java
https://github.com/confluentinc/kafka-connect-storage-cloud/issues/449
This `toString()` is hurting performance when using the S3 sink with the Parquet output format.
Just remove the `toString()`. it's not necesary.
Running this manually, performance is improved.
This only applies to the `5.5.x` line. The equivalent code in `master` looks like it was fixed when other new features were implemented
> Remove toString() call in trace log

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/TopicPartitionWriter.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/TopicPartitionWriterTest.java
If there are no records in the buffer and no open files and 1000 new records are pushed to a topic at the same time then should these 1000 records be part of a single new file.
Currently, the task creates 2 new files (1 with 1st record and another with rest of the 999 records). This happens because we use the arrival of first record to determine that scheduled rotation has expired and reset the nextScheduledRotation causing a record with 1 file to roll.
We should reset the nextScheduledRotation even if there are no records to commit and time has passed.
Merging https://github.com/confluentinc/kafka-connect-storage-cloud/pull/468 to 5.4.x here
- [ X] yes
5.5.x, 10.0.x branches
GCS and AzureBlob sink connector
> CCMSG-1582 Fix bug that generates a small files when scheduled rotation has expired

- kafka-connect-s3/src/test/java/io/confluent/connect/s3/TopicPartitionWriterTest.java
…
fixed a build error in testcase happened due to merge of fixes from 5.5.3 https://github.com/confluentinc/kafka-connect-storage-cloud/pull/473
> CCMSG-1582 fixed a build error in testcase happened due to merge from upstream

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/parquet/ParquetRecordWriterProvider.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/DataWriterParquetTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/TestWithMockedS3.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/TopicPartitionWriterTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/integration/S3SinkConnectorIT.java
Optional array items may be null.  Parquet writer throws a NullPointerException when it comes across this situation.
Situation is described in detail in this issue:
https://github.com/confluentinc/kafka-connect-storage-cloud/issues/339
If a schema contains an array with optional items (String or otherwise), set the "parquet.avro.write-old-list-structure" flag in the AvroParquetWriter object to 'false', and thus the situation will be correctly handled.
1. Test to verify that this flag will do as expected for a schema with an optionall array element (some set to null)
2. Test Extensive permutation of optional/non-optional arrays and nesting tests to assure that schemas with/without an array of optional item will be correctly recognized.
> CCMSG-1531 Support null items within arrays with Parquet writer

- kafka-connect-s3/src/test/java/io/confluent/connect/s3/integration/S3SinkConnectorIT.java
> MINOR: Suppress warning which causes IntelliJ to error after Maven import (via -Werror)

- kafka-connect-s3/src/test/java/io/confluent/connect/s3/integration/S3SinkConnectorIT.java
> MINOR: Suppress warning which causes IntelliJ to error after Maven import (#489)

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/avro/AvroRecordWriterProvider.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/json/JsonRecordWriterProvider.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/parquet/ParquetRecordWriterProvider.java
Did some debugging and verified that it is, in fact, possible for a retriable exception to be thrown during close().  Currently it appears that this won't be retried if it's during a task close(), but that's another matter (that maybe should be addressed separately).
> CCMSG-1481 Retriable exception is possible to be thrown from close()

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/S3RetriableRecordWriter.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/avro/AvroRecordWriterProvider.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/bytearray/ByteArrayRecordWriterProvider.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/json/JsonRecordWriterProvider.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/parquet/ParquetRecordWriterProvider.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/storage/IORecordWriter.java
Duplicated catch/throw logic for each format's RecordWriter with respect to retriable AWS exceptions.
Consolidte the catch/rethrow logic for AWS retriable exceptions by wrapping the anonymous format classes as they are created. Wrapper is intentionally as close as possible to the call/throw sites rather than up another level (or more) in KeyValueHeaderRecordWriterProvider.
No behavioral changes should occur.
Suggest turning off whitespace in comparison since blocks of code were simply shifted right one tab in many places.
> Generalize S3 record writes with wrapper to possibly convert to RetriableException

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkConnectorConfig.java
validValues() returns singleton list of a list of 27 regions, making the single-selectable item a list of 27 items. It is impossible to set a region in CP due to this.
> Fix regions list being one item of a list

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/KeyValueHeaderRecordWriterProvider.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/avro/AvroRecordWriterProvider.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/bytearray/ByteArrayRecordWriterProvider.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/json/JsonRecordWriterProvider.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/parquet/ParquetRecordWriterProvider.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/util/Utils.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/TopicPartitionWriterTest.java
SinkRecord was being logged in TRACE message exposing confidential data
only log the topic+partition+offset for the record instead of contents
> CCMSG-1833 Remove the logging of sink record in TRACE message 

- pom.xml
Build failing due to confluent-log4j was removed from `common` (https://github.com/confluentinc/common/pull/451). 
confluent-log4j is already pinned in storage-common (https://github.com/confluentinc/kafka-connect-storage-common/blob/1b29e67590ffa74574b0ce7eef5e238ccb14f1e6/pom.xml#L73) 
Other connectors using storage-common and messed confluent-log4j.
> Fix build by removing pinning of confluent-log4j dependency

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkConnectorConfig.java
Jira ticket : https://confluentinc.atlassian.net/browse/CCMSG-1577
The label for Compression Level config is incorrect in the S3 Sink connector for Confluent Platform
In the S3 sink connector Confluent Platform the label for the config 's3.compression.level' is incorrectly set as 'Compression Type' . Look at the screen shot attached which shows how the config label looks in Confluent Platform.
We must rename that label to 'Compression Level'
> CCMSG-1577 label change to compression level for s3 sink connector

- pom.xml
11.0.x points to unreleased `common`  7.x
Revert back 11.0.4 to 10.2.4 `kafka-connect-storage-common-parent`. 
kafka-connect-hdfs -> also uses 11.0.x kafka-connect-storage-common-parent version
Release a patch version on 10.0.x
> Revert parent pom back 11.0.4 to 10.2.4

- pom.xml
Recently parent pom was downgraded to 10.2.4 because 11.0.x points to unreleased `common`  7.x.
Reverting again to 11.0.x as 7.2 common has been released
Release a patch version on 10.0.x
> Update parent pom to 11.0.9

- pom.xml
[CCMSG-2014](https://confluentinc.atlassian.net/browse/CCMSG-2014): Vulnerable dependency "parquet:parquet-format-structures" for kafka-connect-storage-cloud:master-latest
- Updated parquet version in kafka-connect-storage-common
- Use latest kafka-connect-storage-common with updated parquet version as parent
```
➜  kafka-connect-storage-cloud git:(10.0.x) ✗ mvn dependency:tree | grep parquet
[INFO] |  +- org.apache.parquet:parquet-column:jar:1.12.3:compile
[INFO] |  |  +- org.apache.parquet:parquet-common:jar:1.12.3:compile
[INFO] |  |  |  \- org.apache.parquet:parquet-format-structures:jar:1.12.3:compile
[INFO] |  |  +- org.apache.parquet:parquet-encoding:jar:1.12.3:compile
[INFO] |  \- org.apache.parquet:parquet-avro:jar:1.12.3:compile
[INFO] |     \- …
```
> CCMSG-2014: Upgrade storage-common-parent version to remove parquet vulnerability

- pom.xml
CCMSG-1974: Vulnerable dependency "org.slf4j_slf4j-log4j12:1.7.25" for kafka-connect-storage-cloud:master-latest
CCMSG-1970: Vulnerable dependency "org.slf4j_slf4j-log4j12:1.7.26" for kafka-connect-storage-cloud:5.5.x-latest
CCMSG-1972: Vulnerable dependency "org.slf4j_slf4j-log4j12:1.7.26" for kafka-connect-storage-cloud:5.4.x-latest
- Remove indirect dependency on slf4j-log4j12
- Add an explicit dependency on slf4j-reload4j
- Note: slf4j-reload4j version has been added to kafka-connect-storage-common
Removed all dependency on `slf4j-log4j12` for this repo:
```
➜  kafka-connect-storage-cloud git:(CCMSG-1972) mvn dependency:tree -Dincludes=org.slf4j:slf4j-log4j12
[INFO] --------------< io.confluent:kafka-connect-storage-cloud >--------------
[INFO] Building kafka-connect-storage-cloud …
```
> CCMSG-1974: CVE - remove dependency on slf4j-log4j and add dependency on sl4j-reload4j

- README.md
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkConnectorConfig.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkTask.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/TopicPartitionWriter.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/util/RetryUtil.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/S3SinkConnectorConfigTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/S3SinkTaskTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/TopicPartitionWriterTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/integration/S3SinkConnectorIT.java
[CCDB-4880](https://confluentinc.atlassian.net/browse/CCDB-4880): Databricks Delta Lake Sink Connector sporadically fails with a NPE when trying to read "endOffset" tag from S3 objects. The root cause is that the Delta Lake Sink Connector under the hood leverages S3 Sink Connector code to write/create S3 objects and the S3 Sink Connector code in case of any tagging errors simply ignores them. However from Databricks Sink Connector POV ignoring such tagging errors means the S3 object is left in an inconsistent state because it expects that if object is there in S3 then tag must also be there for that S3 object. See discussions in this [slack thread](https://confluent.slack.com/archives/C011CCECDB7/p1660623278820309).
Adding a S3 Sink Connector low level configuartion so that the …
> CCDB-4880: Adding a S3 Sink Connector config to modify behavior w.r.t tagging errors.

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkConnectorConfig.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/auth/AwsAssumeRoleCredentialsProvider.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/storage/S3Storage.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/S3SinkConnectorConfigTest.java
Allow S3 sink to use assume role with aws.access.key.id
when the connector uses aws.access.key.id it defaults to the BasicAWSCredential ignoring the assume role configs.
As part of solution, I hve introduced a check to find out which Provider has been configured by customer and instantiate appropriate provider.
Also, customer doesn't have to keep creds and roles info in .aws/credentials file now for Assumed role because 
we are creating StsClient with configured aws.access.key.id and aws.secret.access.key. If aws.access.key.id and aws.secret.access.key are not configured in connector, default stsclient will look for creds in aws/credential file. 
Steps to test Assume Role :
1-  AWS account-1 (pooja-aws-devel)
2- Log into to the AWS management web console for the DEVEL account.
3- Create a …
> CCMSG 1074 - Allow S3 sink to use assume role with aws.access.key.id

- pom.xml
Bumping up the version of parent kafka-connect-storage-common to address:
* Version updates coming for other CVE fixes
* log4j(https://github.com/confluentinc/kafka-connect-storage-common/pull/268)
* derby (https://github.com/confluentinc/kafka-connect-storage-common/pull/266)
* hadoop (https://github.com/confluentinc/kafka-connect-storage-common/pull/269)
* Bug Fix for https://github.com/confluentinc/kafka-connect-storage-cloud/issues/553
For https://github.com/confluentinc/kafka-connect-storage-cloud/issues/553, check PR description in https://github.com/confluentinc/kafka-connect-storage-common/pull/273
Release as new patch version
> Update storage common version

- pom.xml
[CCMSG-2287](https://confluentinc.atlassian.net/browse/CCMSG-2287) - Upgrade jettison at kafka-connect-storage-cloud
[CCMSG-2293](https://confluentinc.atlassian.net/browse/CCMSG-2293) - Upgrade org.apache.hadoop:hadoop-common at kafka-connect-storage-cloud
1- modifying hadoop-common version to  3.2.3.
2- And adding jettison dependency with version 1.5.1 explicitly.
<--- Snippet from dependency listing--->
[INFO] +- commons-beanutils:commons-beanutils:jar:1.9.4:compile
[INFO] +- org.codehaus.jettison:jettison:jar:1.5.1:compile
[INFO] +- org.apache.hadoop:hadoop-mapreduce-client-core:jar:3.2.3:test
[INFO] |  +- org.apache.hadoop:hadoop-yarn-client:jar:3.2.3:test
[INFO] |  |  \- org.apache.hadoop:hadoop-yarn-api:jar:3.2.3:test
+- org.apache.hadoop:hadoop-common:jar:3.2.3:compile
[INFO] |  +- …
> bumping hadoop and jettison version

- pom.xml
Hadoop-common 3.2.3 imports common-lang3 but code needs common-lang.
Added common-lang explicitly to pom.xml
> updating pom.xml to add missing common-lang dependency

- pom.xml
IT test cases are failing .
excluding jetty related dependencies from hadoop-common.
> excluding jetty related dependencies

- pom.xml
Release build is failing due to incorrect version 
fixed the version to kafka.connect.storage.common.version
> fixing release issue in 5.4.x

- pom.xml
Vulnerable dependency "com.fasterxml.woodstox_woodstox-core:5.3.0" for kafka-connect-storage-cloud:master-latest
Explicitly add woodstox with 5.4.0 as hadoop-common extracts 5.3.0 version
Docker-PlayGround Test Results :
> CCMSG-2267 - Vulnerable dependency "com.fasterxml.woodstox_woodstox-core:5.3.0" for kafka-connect-storage-cloud:master-latest

- pom.xml
https://confluentinc.atlassian.net/browse/CCMSG-2336
Explicitly add woodstox with 5.4.0 as hadoop-common extracts 5.3.0 version
> Vulnerable dependency "com.fasterxml.woodstox_woodstox-core:5.3.0" for kafka-connect-storage-cloud:5.4.x-latest

- pom.xml
Currently, Unable to release 5.4.x and 5.5.x because SNAPSHOT versions are getting imported   
] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare (default-cli) on project kafka-connect-storage-cloud: Can't release project due to non released dependencies :
17:47:21  [ERROR]     io.confluent:kafka-connect-storage-common:jar:5.4.11-SNAPSHOT:compile
17:47:21  [ERROR]     io.confluent:kafka-connect-storage-core:jar:5.4.11-SNAPSHOT:compile
17:47:21  [ERROR]     io.confluent:kafka-connect-storage-format:jar:5.4.11-SNAPSHOT:compile
17:47:21  [ERROR]     io.confluent:kafka-connect-storage-partitioner:jar:5.4.11-SNAPSHOT:compile
17:47:21  [ERROR] in project 'kafka-connect-storage-cloud' (io.confluent:kafka-connect-storage-cloud:pom:5.4.11-SNAPSHOT)
17:47:21 …
> Fixing release issues for 5.4.x

- kafka-connect-s3/pom.xml
- pom.xml
In recent release, I made a few changes to release this connector for 5.4.x and 5.5.x branches which led the problems in packaging.
Restoring 5.5.x to its previous state [changes releated to CVEs are kept intact]
> Restoring 5.5.x to solve packaging issue.

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkConnectorConfig.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkTask.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/util/SchemaPartitioner.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/S3SinkConnectorConfigTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/TopicPartitionWriterTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/storage/S3StorageTest.java
- pom.xml
https://confluentinc.atlassian.net/browse/CCMSG-2232
Will expose subject name strategy in cloud template; for an on-prem customer can easily override the value converter config.
Added Schema based partitioner for supporting multiple writers for different schemas
Manually tested in CP:
Attached screenshots with json data, json data with schema in payload (schema2), schema in sr:
Screenshot with prefix:
Suffix Screenshot:
> CCMSG-2232: Add support for topic record name strategy

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkConnectorConfig.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkConnectorValidator.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkTask.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/TopicPartitionWriter.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/KeyValueHeaderRecordWriterProvider.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/util/TombstoneSupportedPartitioner.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/util/TombstoneTimestampExtractor.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/integration/BaseConnectorIT.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/integration/S3SinkConnectorIT.java
This PR adds a third option to behavior.on.null.values to write the tombstone records. It also introduces a new config tombstone.encoded.partition.
It creates a new decorator to the existing partitioner to redirect all the tombstone records to tombstone.encoded.partition when the tombstone write option is enabled.
The key writer becomes mandatory while sinking tombstone records.
Sinking of tombstone records to a separate output directory is a design choice made so as to avoid interleaving regular records with tombstone records.  This would trigger aggressive schema based rotations everytime a tombstone is encountered (resulting into a lot of small files being generated). Once while transitioning from some schema -> null and then while transitioning from null -> some schema.
> CCMSG-2361 | Support writing of tombstone records.

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/auth/AwsAssumeRoleCredentialsProvider.java
[CCMSG-2368](https://confluentinc.atlassian.net/browse/CCMSG-2368): Some customers reported seeing 427 (throttles) from AWS STS service because we are not caching STS assume role call's credentials. 
- Start caching  credentials fetched vis STSAssumeRoleCredential provider
- AWS sdk's STSAssumeRoleCredentialProvider implementation already takes care of refreshing the fetched temp creds via a background [thread](https://github.com/aws/aws-sdk-java/blob/6059d1033b8be1de544f679732e18220d22a848a/aws-java-sdk-sts/src/main/java/com/amazonaws/auth/STSAssumeRoleSessionCredentialsProvider.java#L34-L48) before expiry
Tested manually for CP
Release a patch version
> CCMSG-2368: Cache short-lived credentials when using AWSAssumeRoleCredentialProvider

- pom.xml
An update to hadoop in kafka-connect-storage-cloud reintroduced this vulnerability due to a shaded jar: nimbus-jose-jwt-9.8.1.jar
The dependency com.nimbusds:nimbus-jose-jwt:jar:9.8.1  comes as follows -
```
io.confluent:kafka-connect-s3:jar:*-SNAPSHOT
org.apache.hadoop:hadoop-common:jar:3.2.4:compile
org.apache.hadoop:hadoop-auth:jar:3.2.4:compile
com.nimbusds:nimbus-jose-jwt:jar:9.8.1:compile
```
All below tickets have reported the same jar issue in different branches. 
[CCMSG-2359](https://confluentinc.atlassian.net/browse/CCMSG-2359): Vulnerable dependency "net.minidev_json-smart:1.3.2" for kafka-connect-storage-cloud:5.5.x-latest
[CC-18749](https://confluentinc.atlassian.net/browse/CC-18749): Request to fix CVE-2021-31684: net.minidev_json-smart in kafka-connect-storage-cloud …
> CC-18749 CVE fix : Pins nimbus-jose-jwt version in pom.xml 

- pom.xml
- https://confluentinc.atlassian.net/browse/CC-18575
- commons-net dependency has a CVE which is coming from hadoop-common parent dep. 
- Exclude this CVE dependency from parent dependency. 
- Manual testing on kafka-docker-playground.
> CC-18575: Exclude commons-net from hadoop-common dependency

- pom.xml
Build is failing with following error - 
```
The project io.confluent:kafka-connect-storage-cloud:10.0.17-SNAPSHOT (/home/jenkins/workspace/fka-connect-storage-cloud_PR-611/pom.xml) has 1 error
10:38:32  [ERROR]     Non-resolvable parent POM for io.confluent:kafka-connect-storage-cloud:10.0.17-SNAPSHOT: Could not transfer artifact io.confluent:kafka-connect-storage-common-parent:pom:11.0.18 from/to confluent (${confluent.maven.repo}): Cannot access ${confluent.maven.repo} with type default using the available connector factories: BasicRepositoryConnectorFactory and 'parent.relativePath' points at wrong local POM @ line 21, column 13: Cannot access ${confluent.maven.repo} using the registered transporter factories: WagonTransporterFactory: Unsupported transport protocol -> [Help 2]
```
- …
> Minor: Remove property confluent.maven.repo and use url directly

- pom.xml
- https://confluentinc.atlassian.net/browse/CC-18978
- protobuf java vulnerable version
- Bring in latest version of kafka-connect-storage-common which has fix - https://github.com/confluentinc/kafka-connect-storage-common/pull/300
> Minor: Bump kafka-connect-storage-common version to 11.0.19 to fix CVEs

- pom.xml
> CCMSG-2338 | Bump up jetty-io dependency version to fix the CVE.

- pom.xml
> CCMSG-2338 | Bump jetty-io dependency version to 9.4.48.v20220622

- pom.xml
> MINOR: Pin parquet dependency version to 1.11.2

- pom.xml
jetty-webapp 9.4.43.v20210629 is a CVE as mentioned here - 
https://confluentinc.atlassian.net/browse/CCMSG-2346?focusedCommentId=1440477
Exclude the dependency as it is not required.
> CCMSG-2346 | Exclude jetty-webapp as compile scope dependency.

- pom.xml
SnakeYaml brought in as transitive dependency of Schema Registry is affected by CVE-2022-1471
Pin the SnakeYaml dependency version until non vulnerable version will be brought in from an updated Schema Registry
> CCMSG-2432 Update SnakeYaml to address CVE-2022-1471

- pom.xml
https://confluentinc.atlassian.net/browse/CC-20979
https://confluentinc.atlassian.net/browse/CC-20978
https://confluentinc.atlassian.net/browse/CC-20329
https://confluentinc.atlassian.net/browse/CC-20736
Pinning snappy version since it is originating from kafka-clients package which is set in common module.
```
[INFO]
[INFO] --- dependency:2.8:tree (default-cli) @ kafka-connect-s3 ---
[INFO] io.confluent:kafka-connect-s3:jar:3.2.5-SNAPSHOT
[INFO] +- com.amazonaws:aws-java-sdk-s3:jar:1.11.725:compile
[INFO] |  +- com.amazonaws:aws-java-sdk-kms:jar:1.11.725:compile
[INFO] |  +- com.amazonaws:aws-java-sdk-core:jar:1.11.725:compile
[INFO] |  |  +- commons-logging:commons-logging:jar:1.1.3:compile
[INFO] |  |  +- org.apache.httpcomponents:httpclient:jar:4.5.9:compile
[INFO] |  |  |  \- …
```
> [CC-20979] [CC-20329] Updated CVEs (jackson and snappy package)

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkConnectorConfig.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/format/json/JsonFormat.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/S3SinkConnectorConfigTest.java
Added support for decimal.format config to be passed to json formatter.
> CC-21917 | Added support for decimal.format config to be passed to json formatter.

- kafka-connect-s3/src/assembly/package.xml
- pom.xml
Excluding `hadoop-shaded-guava` for CVE fix in commit https://github.com/confluentinc/kafka-connect-storage-cloud/commit/8a80a19363f5c8d89d7b52367352a25b1ff1de8b
resulted in a regression with `NoClassDefFoundError: org/apache/hadoop/thirdparty/com/google/common/collect/Interners`
while using the `io.confluent.connect.s3.format.parquet.ParquetFormat` for `format.class` field in config.
[kafka-connect-storage-common](https://github.com/confluentinc/kafka-connect-storage-common/tree/master) has an updated hadoop-shaded-guava without the CVE.
> Fix for regression from CVE fix in PR #660

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/storage/S3OutputStream.java
For [this](https://confluent.slack.com/archives/C05PEERD0A2) on call issue, [this PR](https://github.com/confluentinc/kafka-connect-storage-cloud/pull/477) fixes the problem, as a JAR was made and shared with customer to which they responded affirmatively. 
Now they want a global release for this, hence putting this patch in all branches 10.0.x onwards.
> Removed x-amz-server-side-encryption to get SEE-C working

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkConnectorConfig.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/TopicPartitionWriter.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/S3SinkConnectorConfigTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/TopicPartitionWriterTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/integration/S3SinkDataFormatIT.java
Currently, there is a boolean field `s3.object.tagging` in the Kafka Connect sink to S3 config. If set to `true`,connector adds s3 object level tags for starting offset, ending offset, and total record count of a given file. Furthermore, we would like to make Kafka Connect sink to S3 able to sink S3 object with configurable tags. This is extremely valuable if users want to manage S3 Object lifecyle based on S3 tags.
Ultimately, this PR solve issue https://github.com/confluentinc/kafka-connect-storage-cloud/issues/68
To add two extra fields `s3.object.tagging.key` and `s3.object.tagging.value` for users to specify their own key value pairs. `s3.object.tagging` must also be set to `true` as pre-requisite
> Add suport for custom S3 object tagging

- pom.xml
https://confluent.slack.com/archives/C06HJ2VFQ5T  
While projecting we were changing instance of record from InternalSinkRecord to SinkRecord and while reporting we were using modified records which was causing the original schema of messages to be changed while serialising again.
Update version of common to 11.2.5. 
https://github.com/confluentinc/kafka-connect-storage-common/pull/347
> Update common version to fix record reporting

- kafka-connect-s3/src/test/java/io/confluent/connect/s3/S3SinkConnectorFaultyS3Test.java
The test is failing with error:
```
[ERROR] Errors: 
[ERROR]   S3SinkConnectorFaultyS3Test.startConnect:140 ? Connect One or more plugins are missing ServiceLoader manifests may not be usable with plugin.discovery=service_load: [
classpath       io.confluent.connect.avro.AvroConverter converter       undefined
classpath       io.confluent.connect.json.JsonSchemaConverter   converter       undefined
classpath       io.confluent.connect.protobuf.ProtobufConverter converter       undefined
classpath       io.confluent.connect.s3.S3SinkConnector sink    10.0.28-SNAPSHOT
classpath       io.confluent.connect.storage.tools.SchemaSourceConnector        source  7.6.0-207-ccs
]
```
Set plugin.discovery to hybrid_warn, similar to [here](https://github.com/confluentinc/kafka-connect-storage-cloud/blob …
> Fix S3SinkConnectorFaultyS3Test

- pom.xml
CVE-2024-23944: It allows an attacker to monitor child znodes by attaching a persistent watcher (addWatch command) to a parent which the attacker has already access to. ZooKeeper server doesn\'t do ACL check when the persistent watcher is triggered and as a consequence, the full path of znodes that a watch event gets triggered upon is exposed to the owner of the watcher. It\'s important to note that only the path is exposed by this vulnerability, not the data of znode, but since znode path can contain sensitive information like user name or login ID, this issue is potentially critical. 
Users are recommended to upgrade to version 3.9.2, 3.8.4 which fixes the issue. But since zookeeper dependency comes from hadoop-common, and we do not have any version which have this cve fixed, so we have …
> CC-26046: Pinned zookeeper version

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/TopicPartitionWriter.java
In case of any malformed record failing due to SchemaParseException or InvalidSchemaException, connector fails with an error instead of adhering to errors.tolerance parameter
Catch the related exceptions and write the error to dlq topic based on the configured dlq and errors.tolerance
> CC-24623 Handle SchemaParseException and InvalidSchemaException according to errors.tolerance

- pom.xml
Existing joda-time version used does not work with daylight savings in certain timezones resulting in incorrect time partitioning
Bump kafka-connect-storage-common-parent version which brings in updated joda-time version
> CC-27029 Bump kafka-connect-storage-common-parent version to update joda version

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkConnectorConfig.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/storage/S3OutputStream.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/S3SinkConnectorConfigTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/S3SinkTaskTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/integration/S3SinkConnectorIT.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/storage/S3OutputStreamDigestTest.java
https://github.com/confluentinc/kafka-connect-storage-cloud/issues/760, https://github.com/confluentinc/kafka-connect-storage-cloud/issues/710: S3 Object Locking requires an MD5 digest to be sent with the multipart upload request, otherwise it will be rejected.
Include new option, `s3.send.digest`, that when set to `true` will include MD5 digest with upload parts.
Merge to master.
Developed in conjunction with @paul-dellinger
> s3.send.digest option, default false

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkConnectorConfig.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkTask.java
Problem:
The connector sends null records to dlq if dlq is enabled and behaviour.on.null is set to ignore. But, if errors.tolerance is set to none, the connector fails as it sends the record with DataException to dlq. In such a case, there is no way for a customer to use both dlq(for other errors) and errors.tolerance is set to noneforbehaviour.on.nullis set toignore.
Solution:
This PR adds a simple config to skip writing to dlq in such an edge case
Testing:
Manually verified on docker-playground
> CC-26094 Add config to disable writing null records to dlq (#2)

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/TopicPartitionWriter.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/TopicPartitionWriterTest.java
Committing open files on partition change results in creating a lot of small files when records belonging to different partitioned are interleaved.  We have a use case where we aggregate raw events into sessions spanning for 5-15 minutes with session time being the time of the first event in it. We use hourly partitioning and observe  up to 10x increase in number of files per hour due to this.
The issue has been reported multiple time previously:
- https://github.com/confluentinc/kafka-connect-storage-cloud/issues/380
- https://github.com/confluentinc/kafka-connect-storage-cloud/issues/529
And even had an attempted fix:
- https://github.com/confluentinc/kafka-connect-storage-cloud/pull/574
Removing rotation on partition changes makes the semantics of `rotate.interval.ms` similar to …
> stop rotating on partition change when rotate.interval.ms is set

- pom.xml
CC-29502: Vulnerable dependency "org.apache.avro_avro:1.11.3" for kafka-connect-[storage-cloud](https://confluentinc.atlassian.net/browse/STORAGE-cloud):master-latest
Bump apache avro to 1.11.4
Docker Playground Run
> CC-29502: Bumped kakfa-connect-storage-cloud

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/storage/S3OutputStream.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/storage/S3OutputStreamTest.java
The connector does not add `x-amz-server-side-encryption` header when SSE is set to AES256 and no customer key is specified. This results in connector failing in cases where the IAM policy expects `x-amz-server-side-encryption` to be set.
Add the SSE related metadata to init request when customer key is not null
> CC-29553 Fix connector to work with SSE-S3

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkConnectorConfig.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkTask.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/TopicPartitionWriter.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/TopicPartitionWriterTest.java
This PR adds a time out to the put loop to add a limit on maximum amount of time a task can spend in the poll cycle
If the task spends significant amount of time in poll loop, it will likely become a zombie.
Hence, adding a timeout can prevent a zombie task from processing the files
Manually tested by adding random sleep in the task and ensuring that the task reaches deadline in such cases
> CC-29764 Add timeout to sink put cycle

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkConnectorConfig.java
The Kafka commons Utils class removed the "join" method in https://github.com/apache/kafka/pull/15823 in Kafka 3.8. Due to this reason the connector stopped working on Kafka Connect 3.8 as well.
Following the example in the upstream PR, I'm replacing the usage of Utils.join with the JDK API of String.join, and updating the code accordingly.
This is a new version of [PR #804](https://github.com/confluentinc/kafka-connect-storage-cloud/pull/804), but rebased for 10.0.x. Fixes [Issue #781](https://github.com/confluentinc/kafka-connect-storage-cloud/issues/781)
Its safe to merge to master
> MINOR: Replace Kafka Utils.join() with JDK API

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkConnectorConfig.java
Fixes checkstyle failure introduced by https://github.com/confluentinc/kafka-connect-storage-cloud/pull/810
> Fix checkstyle

- pom.xml
Removing protobuf-shaded and netty-common dependencies.
Tested with docker playground with AVRO and parquet formats.
> Fedramp CVE fixes

- pom.xml
Hadoop-common's dependency `org.bouncycastle:bcprov-jdk15on:1.70` has CVEs CVE-2024-30171 and CVE-2024-29857.
Bump up hadoop-common to 3.4.1
This will switch the dependency to `org.bouncycastle:bcprov-jdk18on:jar:1.78`. 
(jdk15on has been moved to jdk18on - https://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk15on)
> CC-31172: Bump hadoop-common to 3.4.1

- kafka-connect-s3/pom.xml
Bumping AWS version to `1.12.750` to support eksPodIdentity for IAM Role assumption
Validated in devel canary, connector is working fine with this change
> Bump AWS version

- kafka-connect-s3/pom.xml
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkConnectorConfig.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/TopicPartitionWriter.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/errors/FileExistsException.java
- kafka-connect-s3/src/main/java/io/confluent/connect/s3/storage/S3OutputStream.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/S3SinkConnectorConfigTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/TopicPartitionWriterTest.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/integration/BaseConnectorIT.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/integration/S3SinkConnectorIT.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/integration/S3SinkDataFormatIT.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/storage/S3OutputStreamTest.java
- Adds a config to enable conditional writes, the default being true
- The conditional write will be enabled only when scheduled interval is set and store kafka key/headers config is disabled to retain the existing delivery semantics
- On a conditional write exception, a FileExistsException is rethrown , which being a retriable exception will reset the offset and poll again accordingly
- In case of FileExistsException, connector will scan the s3 bucket for next available file which is not present in S3 by making consecutive get object requests. If the get api fails with 403 error, it will simply increment to next offset.
- To enable determining the next available file, the equivalent target file name is cached for initial few records, had the record been the first record in the file. The …
> CC-31153 Enable conditional writes in connector

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/storage/S3OutputStream.java
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/storage/S3OutputStreamTest.java
Add additional checks to confirm file exists in S3 after a 412 error from S3
- Add additional call to S3 to confirm file exists in S3 before returning a FileExistsException. Even though this adds an additional api call, it should be fine since the subsequent scanning for files in S3 will anyways happen to get next available offset.
- This also fixes the condition where s3 returned 200 ok status with PreConditionFailed error
```
com.amazonaws.services.s3.model.AmazonS3Exception: At least one of the pre-conditions you specified did not hold (Service: Amazon S3; Status Code: 200; Error Code: PreconditionFailed; Request ID: 8F1YK0DTDWAY6277; S3 Extended Request ID: yyiZ80A38ykXjJ2HgAMUayESZ4Cfte2HPoxYtpwgT+H8EAbiUsD72EWWH1nxHbraTxG5Fkv+680=; Proxy: null), S3 Extended Request ID: …
```
> CC-32742 Add additional checks to confirm file exists in S3

- kafka-connect-s3/pom.xml
- kafka-connect-s3/src/test/java/io/confluent/connect/s3/integration/BaseConnectorIT.java
- pom.xml
Bumped parquet-avro dependency.
parquet-tools dependency used in test is not compatible with latest parquet-avro dependency and hence, it has been removed and added logic to read parquet files using parquet reader
```
➜  kafka-connect-s3 git:(CC-33012/parquet-bump) ✗ mvn dependency:tree | grep parquet-
[INFO] |  +- org.apache.parquet:parquet-column:jar:1.15.1:compile
[INFO] |  |  +- org.apache.parquet:parquet-common:jar:1.15.1:compile
[INFO] |  |  |  \- org.apache.parquet:parquet-format-structures:jar:1.15.1:compile
[INFO] |  |  \- org.apache.parquet:parquet-encoding:jar:1.15.1:compile
[INFO] |  \- org.apache.parquet:parquet-avro:jar:1.15.1:compile
[INFO] |     \- org.apache.parquet:parquet-hadoop:jar:1.15.1:compile
```
> CC-33012 Bump parquet-avro dependency

- kafka-connect-s3/src/main/java/io/confluent/connect/s3/auth/AwsAssumeRoleCredentialsProvider.java
Allow configuring sts region
Add a config to determine the region to use when creating sts client.
When this config is not, aws default region provider will be used by the sdk
> CC-33303 Add STS client region to builder

- kafka-connect-s3/pom.xml
- pom.xml
The version was wrongly set to 10.7.0 instead of 11.0 during release cut.
Manually fixes the versions
> Fix artifact versions in pom

- kafka-connect-s3/pom.xml
- pom.xml
The vulnerability identified in [CC-35444](https://confluentinc.atlassian.net/browse/CC-35444) persists because 'commons-lang3' is still included transitively through the 'hadoop-common' dependency, even after the partial resolution in [PR #879](https://github.com/confluentinc/kafka-connect-storage-cloud/pull/879). 
To fully address this issue, we pinned the version in the 'dependencyManagement' in the 'pom' files.
kdp
[CC-35444]: https://confluentinc.atlassian.net/browse/CC-35444?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix CVE : commons-lang3
